"""Publish built figures into the research-notes MkDocs site.

Destination layout (under ``research_notes / docs / figures``):

    figures/<paper>/<figure_id>/<figure_id>.{png,svg,pdf}
    figures/<paper>/<figure_id>/CAPTION.md
    figures/<paper>/<figure_id>/metadata.json
    figures/<paper>/index.md     (grid of that paper's figures)

Figures missing a ``paper`` metadata tag are skipped (publish-to-notes is
paper-scoped). Use ``--paper J3`` to publish only one paper, or
``--dry-run`` to preview without writing.

Usage (from the figure_generator repo root):

    python scripts/publish_to_notes.py
    python scripts/publish_to_notes.py --paper J3
    python scripts/publish_to_notes.py --paper J3 --dry-run
    FIGGEN_RESEARCH_NOTES=/abs/path/to/notes python scripts/publish_to_notes.py
"""

from __future__ import annotations

import argparse
import json
import shutil
import sys
from pathlib import Path

from figgen import FIGURES_DIR
from figgen.io import research_notes_path
from figgen.metadata import read_png_metadata, read_svg_metadata


_PAPER_INDEX_HEADER = """\
# {paper} — figures

Generated by `figure_generator`. Do not edit by hand; run
`make publish PAPER={paper}` in the figure_generator repo to refresh.

"""

_PAPER_CARD = """\
- :material-image-outline:{{ .lg }} __[{fig_id}]({fig_id}/{fig_id}.png)__

    <span class="chip">{journal}</span>
    {claim_chip}

    ---

    ![{fig_id}]({fig_id}/{fig_id}.png){{ loading=lazy }}

    {caption_excerpt}

    `git:{git_hash}` · `data:{data_sources}`
"""


def _read_metadata(fig_dir: Path, fig_id: str) -> dict[str, str]:
    png = fig_dir / f"{fig_id}.png"
    svg = fig_dir / f"{fig_id}.svg"
    if png.exists():
        return read_png_metadata(png)
    if svg.exists():
        return read_svg_metadata(svg)
    return {}


def _caption_excerpt(fig_dir: Path, limit: int = 220) -> str:
    cap = fig_dir / "CAPTION.md"
    if not cap.exists():
        return ""
    text = cap.read_text(encoding="utf-8")
    lines = [ln for ln in text.splitlines() if ln.strip() and not ln.startswith("#")]
    joined = " ".join(lines)
    return (joined[: limit - 1] + "…") if len(joined) > limit else joined


def _copy_figure(src_dir: Path, dest_dir: Path, fig_id: str, meta: dict[str, str], dry: bool) -> list[Path]:
    dest_dir.mkdir(parents=True, exist_ok=True)
    written: list[Path] = []
    for ext in ("png", "svg", "pdf"):
        src = src_dir / f"{fig_id}.{ext}"
        if src.exists():
            target = dest_dir / src.name
            if not dry:
                shutil.copy2(src, target)
            written.append(target)
    cap_src = src_dir / "CAPTION.md"
    if cap_src.exists():
        cap_dest = dest_dir / "CAPTION.md"
        if not dry:
            shutil.copy2(cap_src, cap_dest)
        written.append(cap_dest)
    meta_dest = dest_dir / "metadata.json"
    if not dry:
        meta_dest.write_text(json.dumps(meta, indent=2, sort_keys=True), encoding="utf-8")
    written.append(meta_dest)
    return written


def _write_paper_index(paper_dir: Path, paper: str, entries: list[dict], dry: bool) -> Path:
    lines = [_PAPER_INDEX_HEADER.format(paper=paper), "<div class=\"grid cards\" markdown>", ""]
    for e in entries:
        claim = e["meta"].get("claim_id", "")
        claim_chip = f'<span class="chip claim">claim: {claim}</span>' if claim else ""
        lines.append(
            _PAPER_CARD.format(
                fig_id=e["figure_id"],
                journal=e["meta"].get("journal", "—"),
                claim_chip=claim_chip,
                caption_excerpt=_caption_excerpt(e["src"]) or "_(no caption)_",
                git_hash=e["meta"].get("git_hash", "n/a"),
                data_sources=e["meta"].get("data_sources", "n/a"),
            )
        )
    lines.append("</div>")
    index = paper_dir / "index.md"
    if not dry:
        index.write_text("\n".join(lines), encoding="utf-8")
    return index


def _scan(paper_filter: str | None) -> list[dict]:
    out: list[dict] = []
    for d in sorted(FIGURES_DIR.iterdir()):
        if not d.is_dir() or d.name.startswith("."):
            continue
        fig_id = d.name
        meta = _read_metadata(d, fig_id)
        paper = meta.get("paper", "").strip()
        if not paper:
            continue  # publish-to-notes is paper-scoped
        if paper_filter and paper != paper_filter:
            continue
        out.append({"figure_id": fig_id, "src": d, "paper": paper, "meta": meta})
    return out


def publish(paper_filter: str | None = None, dry: bool = False) -> dict[str, int]:
    notes_root = research_notes_path()
    if not notes_root.exists():
        raise FileNotFoundError(
            f"research_notes path does not exist: {notes_root}. "
            f"Set FIGGEN_RESEARCH_NOTES or edit configs/paths.yaml."
        )
    figures_root = notes_root / "docs" / "figures"
    figures_root.mkdir(parents=True, exist_ok=True)

    entries = _scan(paper_filter)
    if not entries:
        print("No figures found with a `paper` metadata tag"
              + (f" matching '{paper_filter}'" if paper_filter else "")
              + ". Add `paper: <code>` to the figure's config.yaml and rebuild.")
        return {"figures": 0, "papers": 0}

    by_paper: dict[str, list[dict]] = {}
    for e in entries:
        by_paper.setdefault(e["paper"], []).append(e)

    print(f"→ publishing to {figures_root}{' (dry run)' if dry else ''}")
    for paper, items in sorted(by_paper.items()):
        paper_dir = figures_root / paper
        paper_dir.mkdir(parents=True, exist_ok=True)
        for e in items:
            dest_dir = paper_dir / e["figure_id"]
            paths = _copy_figure(e["src"], dest_dir, e["figure_id"], e["meta"], dry)
            print(f"  [{paper}] {e['figure_id']}: {len(paths)} files")
        _write_paper_index(paper_dir, paper, items, dry)
        print(f"  [{paper}] index.md ({len(items)} figures)")

    return {"figures": sum(len(v) for v in by_paper.values()), "papers": len(by_paper)}


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--paper", help="Publish only figures tagged with this paper code (e.g., J3).")
    parser.add_argument("--dry-run", action="store_true", help="Show what would happen without writing.")
    args = parser.parse_args(argv)
    try:
        stats = publish(paper_filter=args.paper, dry=args.dry_run)
    except FileNotFoundError as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 2
    print(f"done: {stats['figures']} figures across {stats['papers']} paper(s).")
    return 0


if __name__ == "__main__":
    sys.exit(main())
